server:
  port: 8080
  session:
   cookie:
      name: UISESSION
logging:
  level:
    jdbc: error
    jdbc.sqltiming: info
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    